import { Inter } from "next/font/google";
import AdminDashboardSidebar from "../../components/sidebar/adminDashboard/AdminDashboardSidebar.jsx";
import { BiMenuAltLeft } from "react-icons/bi"
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className={inter.className}>
      <div className="relative flex min-h-[600px]">
        <div className="absolute left-0 top-0 w-[250px] min-h-[600px] bg-slate-50">
          <AdminDashboardSidebar />
        </div>
        <div className="relative left-[250px]" style={{width: 'calc(100% - 298px) !important;'}}>
          <div className="absolute">
            <BiMenuAltLeft className="text-[2rem]"/>
          </div>
          <div className="m-6 bg-slate-50 w-full">
          {children}
          </div>
        </div>
      </div>
    </div>
  );
}
