import './globals.css'
import { Inter } from 'next/font/google'
import HeaderComp from '@/app/components/HeaderComp'
import FooterComp from '@/app/components/FooterComp'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderComp/>
        <div>
          {children}
        </div>
        <FooterComp/>
      </body>
    </html>
  )
}
